# Project Information
#
site_name: Programming in a Nutshell
site_url: https://ahayasic.github.io/programming-in-a-nutshell
site_author: Alisson Hayasi da Costa
# site_description:


# Repository
#
repo_name: ahayasic/programming-in-a-nutshell
repo_url: https://github.com/ahayasic/programming-in-a-nutshell
edit_uri: ""


# Copyright
#
copyright: Copyright &copy; 2021 Alisson Hayasi da Costa


# Configuration
#
theme:
  name: material
  custom_dir: docs/overrides
  language: pt

  # Features
  features:
    - content.code.annotate       # allow add simple markers within block/inline comments
    # - content.tabs.link         # make content tabs on a page be linked
    - navigation.instant          # instant reloading
    - navigation.tracking         # url in the address bar automatically updated with the active anchor
    # - navigation.sections       # top-level sections rendered as groups
    # - navigation.expand         # feft sidebar expand all collapsible subsections by default
    - navigation.top              # back-to-top button
    # - header.autohide           # header automatically hidden
    - navigation.indexes          # documents can be directly attached to sections (not working properly!)
    - navigation.tabs             # top-level sections rendered in menu
    # - navigation.tabs.sticky    # lock sections in menu
    - search.highlight            # highlight all occurrences of word searched
    # - search.share              # shareble link to current query search
    - search.suggest              # search display the likeliest completion for the last word
    # - toc.integrate             # toc rendered as part of the navigation

  # Colors
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: amber
      # accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Trocar para Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: amber
      # accent: amber
      toggle:
        icon: material/toggle-switch
        name: Trocar para Modo Claro

  # Font
  font:
    text: Nunito
    code: Fira Mono
    font: false
  # favicon:
  icon:
    repo: fontawesome/brands/github


# Plugins
#
plugins:
  - search
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
      enable_creation_date: true
      exclude:
        - index.md
        - about.md


# Extras
#
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ahayasic/
    - icon: fontawesome/brands/github
      link: https://github.com/ahayasic
    - icon: fontawesome/solid/globe
      link: https://ahayasic.github.io/

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css


# Extensions
#
markdown_extensions:
  # Abbreviations
  - abbr                                                                  # additional content to parts of the text which are then shown on hover

  # Admonitions
  - admonition                                                            # call-outs
  - pymdownx.details                                                      # adds the ability to make admonitions collapsible

  # HTML & CSS
  - attr_list                                                             # add HTML attributes and CSS classes to Markdown elements

  # Code blocks
  - pymdownx.highlight:                                                   # code block highlights
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite                                                 # inline code highlights
  - pymdownx.keys                                                         # allows for inserting keyboard keys

  # Content Tabs
  - pymdownx.tabbed                                                       # allows group alternative content under different tabs

  # Footnotes
  - footnotes                                                             # add the ability to add inline footnotes

  # Text formatting
  - pymdownx.caret                                                        # allow for the highlighting of text, as well as handling sub- and superscripts
  - pymdownx.mark                                                         #
  - pymdownx.tilde                                                        #
  - pymdownx.critic                                                       # allow for the usage of Critic Markup to highlight changes
  - pymdownx.smartsymbols                                                 # converts special characters into their corresponding symbols

  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Lists                                                                 # add support to several flavors of lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # MathJax
  - pymdownx.arithmatex:
      generic: true

  # Meta tags
  - meta                                                                  # adds the ability to add front matter to a document

  # Macros                                                                # add jinja templating support
  # - macros

  # Magic Links                                                           # add ability to link repositories
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ahayasic
      repo: programming-in-a-nutshell

  # Utils
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.snippets                                                     # insert content from other files
  - pymdownx.superfences:                                                 # allows for the nesting of code and content blocks inside admonitions and blocks
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Others
  - md_in_html                                                            # parses Markdown inside of HTML tags.
  - pymdownx.betterem:
      smart_enable: all


# Page tree
#
nav:
  - Início: index.md
  - Sobre o Autor: about.md
  - Programação Orientada à Objetos:
    - oriented_object_programming/index.md
    - Introdução ao Design Orientado à Objetos: oriented_object_programming/introduction.md
    - Classes e Objetos em Python: oriented_object_programming/classes_and_objects_in_python.md
    - Herança, Composição & Polimorfismo: oriented_object_programming/inheritance_composition_and_polymorphism.md
    # - Estudos de Caso:  # TODO
  - Masterizando Python:
    - mastering_python/index.md
    - Guias Definitivos:
      - Importações em Python: mastering_python/definitive_guides/python_imports_guide.md
    - Dicas e Truques: mastering_python/tips_and_tricks/index.md  # Temporary file
  # - Referências: references.md
